//////////////////////////////////////////////////////////////////////////
// Criacao...........: 08/2008
// Sistema...........: Atena - Automacao Clinica Odontologica
// Analistas.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Desenvolvedores...: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Copyright.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
//////////////////////////////////////////////////////////////////////////

program Atena;

uses
  Forms,
  untPrincipal in 'untPrincipal.pas' {frmPrincipal},
  untCadPac in 'untCadPac.pas' {frmCadPac},
  untAnamneseAd in 'untAnamneseAd.pas' {frmAnamneseAd},
  untLembrete in 'untLembrete.pas' {frmLembrete},
  untOdontograma in 'untOdontograma.pas' {frmOdontograma},
  untCadRapid in 'untCadRapid.pas' {frmCadRapid},
  untCadFornec in 'untCadFornec.pas' {frmCadFornec},
  untCadFunc in 'untCadFunc.pas' {frmCadFunc},
  untLocPac in 'untLocPac.pas' {frmLocPac},
  untCadDentista in 'untCadDentista.pas' {frmCadDentista},
  untCadCidade in 'untCadCidade.pas' {frmCadCidade},
  untAgDent in 'untAgDent.pas' {frmAgDent},
  untBloqueio in 'untBloqueio.pas' {frmBloqueio},
  untCadConv in 'untCadConv.pas' {frmCadConv: Unit1},
  untCadProtetico in 'untCadProtetico.pas' {frmCadProtetico},
  untListaEspera in 'untListaEspera.pas' {frmListaEspera},
  untSalaEspera in 'untSalaEspera.pas' {frmSalaEspera},
  untResAgenda in 'untResAgenda.pas' {frmResAgenda},
  untAgendaTel in 'untAgendaTel.pas' {frmAgendaTel},
  untCadTel in 'untCadTel.pas' {frmCadTel},
  untEnvMens in 'untEnvMens.pas' {frmEnvioMens},
  untAgenda in 'untAgenda.pas' {frmAgenda},
  untMarcarCons in 'untMarcarCons.pas' {frmMarcarCons},
  untCadMedicamento in 'untCadMedicamento.pas' {frmCadMedicamento},
  untCadTipoMed in 'untCadTipoMed.pas' {frmCadTipoMed},
  untCadUsoMed in 'untCadUsoMed.pas' {frmCadUsoMed},
  untLocMedic in 'untLocMedic.pas' {frmLocMedic},
  untdmDados in 'untdmDados.pas' {dmDados: TDataModule},
  untCargos in 'untCargos.pas' {frmCargos},
  untDiscar in 'untDiscar.pas' {frmDiscar},
  untCadTipoAtend in 'untCadTipoAtend.pas' {frmCadTipoAtend},
  untCadExames in 'untCadExames.pas' {frmCadExames},
  untCadGrupoEx in 'untCadGrupoEx.pas' {frmCadGrupoEx},
  SkinGraphic in 'SkinGraphic.pas',
  untCadGrupoMed in 'untCadGrupoMed.pas' {frmCadGrupoMed},
  untCadSubGrupo in 'untCadSubGrupo.pas' {frmCadSubGrupo},
  untCadUnidade in 'untCadUnidade.pas' {frmCadUnidade},
  untCadMarca in 'untCadMarca.pas' {frmCadMarca},
  untCadMaterial in 'untCadMaterial.pas' {frmCadMaterial},
  untLocPed in 'untLocPed.pas' {frmLocPed},
  untEstatistica in 'untEstatistica.pas' {frmEstatistica},
  untCadProced in 'untCadProced.pas' {frmCadProced},
  untCadHistorico in 'untCadHistorico.pas' {frmCadHistorico},
  untCadTipoDoc in 'untCadTipoDoc.pas' {frmCadTipoDoc},
  untCadBanco in 'untCadBanco.pas' {frmCadBanco},
  untCadCCorrente in 'untCadCCorrente.pas' {frmCadCCorrente},
  untCadCartao in 'untCadCartao.pas' {frmCadCartao},
  untCadIndice in 'untCadIndice.pas' {frmCadIndice},
  untCadPlanoPagto in 'untCadPlanoPagto.pas' {frmCadPlanoPagto},
  untCPagar in 'untCPagar.pas' {frmCPagar},
  untLocCPagar in 'untLocCPagar.pas' {frmLocCPagar},
  untBaixaLoteCP in 'untBaixaLoteCP.pas' {frmBaixaLoteCP},
  untSelecCP in 'untSelecCP.pas' {frmSelecCP},
  untTipoPagto in 'untTipoPagto.pas' {frmTipoPgto},
  untCancelCP in 'untCancelCP.pas' {frmCancelCP},
  untBaixaLoteCR in 'untBaixaLoteCR.pas' {frmBaixaLoteCR},
  untSelecCR in 'untSelecCR.pas' {frmSelecCR},
  untCancelCR in 'untCancelCR.pas' {frmCancelCR},
  untConfigAnamnese in 'untConfigAnamnese.pas' {frmConfigAnamnese},
  untEncaixe in 'untEncaixe.pas' {frmEncaixe},
  untRelPac in 'untRelPac.pas' {frmRelPac},
  untRelFunc in 'untRelFunc.pas' {frmRelFunc},
  untRelFornec in 'untRelFornec.pas' {frmRelFornec},
  untRelProtetico in 'untRelProtetico.pas' {frmRelProtetico},
  untQRFunc in 'untQRFunc.pas' {QRFunc: TQuickRep},
  untQRPaciente in 'untQRPaciente.pas' {QRPaciente: TQuickRep},
  untQRFornec in 'untQRFornec.pas' {QRFornec: TQuickRep},
  untAnamneseInf in 'untAnamneseInf.pas' {frmAnamneseInf},
  untCadSenha in 'untCadSenha.pas' {frmCadSenha},
  unitCreceber in 'Artemis\UnitCReceber.pas' {frmCReceber},
  unitLanCheque in 'Artemis\UnitLanCheque.pas' {frmLanCheque},
  UnitLocCR in 'Artemis\UnitLocCR.pas' {frmLocCReceber},
  unitLocTipoDoc in 'Artemis\UnitLocTipoDoc.pas' {frmLocTipoDoc},
  UnitTipoReceb in 'Artemis\UnitTipoReceb.pas' {frmTipoReceb},
  unitBaixaCheque in 'Artemis\unitBaixaCheque.pas' {frmBaixaCheque},
  unitLanChequeSF in 'Artemis\unitLanChequeSF.pas' {frmLanChequeSF},
  unitRenCheque in 'Artemis\unitRenCheque.pas' {frmRengCheque},
  unitConsultaCPF in 'Artemis\unitConsultaCPF.pas' {frmConsultaCPF},
  untQRelCheAberto in 'Artemis\untQRelCheAberto.pas' {qrRelCheAberto: TQuickRep},
  unitRelCheAberto in 'Artemis\unitRelCheAberto.pas' {frmRelCheAberto},
  untRelCheDev in 'Artemis\untRelCheDev.pas' {frmRelCheDev},
  untRelCheDevCli in 'Artemis\untRelCheDevCli.pas' {frmRelCheDevCli},
  UnitQRCReceber in 'Artemis\UnitQRCReceber.pas' {QRCreceber: TQuickRep},
  UnitRelCReceber in 'Artemis\UnitRelCReceber.pas' {frmRelCReceber},
  untEntMat in 'Pegasus\untEntMat.pas' {frmEntrMat},
  untSaidaMat in 'Pegasus\untSaidaMat.pas' {frmSaidaMat},
  untCadCompra in 'Pegasus\untCadCompra.pas' {frmCadCompra},
  untPagaPedido in 'Pegasus\untPagaPedido.pas' {frmPagaPedido},
  untLocMat in 'Pegasus\untLocMat.pas' {frmLocMat},
  untLocFornec in 'Pegasus\untLocFornec.pas' {frmLocFornec},
  UnitMovCaixa in 'Artemis\UnitMovCaixa.pas' {frmMovCaixa},
  UnitFechCC in 'Artemis\UnitFechCC.pas' {frmFechCC},
  untQrSaExtratos in 'Artemis\untQrSaExtratos.pas' {QrSaExtrato},
  unitRelMovConta in 'Artemis\unitRelMovConta.pas' {frmRelMovConta},
  unitRelCpagar in 'Artemis\unitRelCpagar.pas' {frmRelCpagar},
  unitQrCpagar in 'Artemis\unitQrCpagar.pas' {QrCpagar},
  untRelEstoque in 'Pegasus\untRelEstoque.pas' {frmRelEstoque},
  untQrInvent2 in 'Pegasus\untqrInvent2.pas' {qrInvent2: TQuickRep},
  untQrTabelaPreco in 'Pegasus\untqrTabelaPreco.pas' {qrTabelaPreco: TQuickRep},
  untQrInventario in 'Pegasus\untqrInventario.pas' {qrInventario: TQuickRep},
  untqrEstoque in 'Pegasus\untqrEstoque.pas' {qrEstoque: TQuickRep},
  untMovDia in 'Pegasus\untMovDia.pas' {qrMovDia: TQuickRep},
  untRelCompPer in 'Pegasus\untRelCompPer.pas' {frmRelCompPer},
  untqrCompra in 'Pegasus\untqrCompra.pas' {qrCompra},
  untRelCompras in 'Pegasus\untRelCompras.pas' {frmRelCompras},
  untqrCompra1 in 'Pegasus\untqrCompra1.pas' {qrCompra1: TQuickRep},
  untCadGrupo in 'Pegasus\untCadGrupo.pas' {frmCadGrupo},
  untQRAnamAd in 'untQRAnamAd.pas' {qrAnamAd: TQuickRep},
  untqrAnamAd2 in 'untqrAnamAd2.pas' {qrAnamAd2: TQuickRep},
  untQRAnamInf in 'untQRAnamInf.pas' {qrAnamInf: TQuickRep},
  untQRAnamInf2 in 'untQRAnamInf2.pas' {qrAnamInf2: TQuickRep},
  untRelNiver in 'untRelNiver.pas' {frmRelNiver},
  untAnive in 'untAnive.pas' {frmAnive},
  untParametro in '..\AtenaP\untParametro.pas' {frmParametro};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TdmDados, dmDados);
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.CreateForm(TfrmRelNiver, frmRelNiver);
  Application.CreateForm(TfrmAnive, frmAnive);
  Application.CreateForm(TfrmParametro, frmParametro);
  Application.Run;
end.
